project:
  type: website
  output-dir: docs

website:
  title: "Aprendizagem de Máquina"
  site-url: https://raphateixeira.github.io/AprendizagemMaquina
  repo-url: https://github.com/raphateixeira/AprendizagemMaquina

  
format:
  html:
    theme: default
    lang: pt-BR
    scss: TemaRTx.scss
    
  revealjs:
    theme: default
    scss: TemaRTx.scss
    transition: slide
    slide-number: true
    footer: "UFPA - NDAE - PPCA - Aprendizagem de Máquina"
    width: 1600      # Largura
    height: 900       # Altura
    code-theme: monokai
    code-font-size: 2.0em
    code-line-numbers: true
    